
:numbered:
== Ongoing Management
:!numbered:

|===
| The purpose of this section is enabling the reader to: +
* Authorize and resource a standards maintenance process essential for maintaining an effective national geospatial information management and sharing environment. +
* Understand how to remain current with advancements in standards through periodic review with standards bodies and communities of practice. +
* Discuss, identify, and submit requirements for standards to address interoperability issues through standards bodies at the organizational, national, and international levels. +
* Understand how they can share experiences and standards success stories with others.
|===

This section is intended for people who are responsible for systems and applications that implement open standards. The systems might be server applications offering standardized interfaces or client applications that consume a standardized interface. The system might also produce or consume data that conforms to one or more data standards. This section focuses on three key areas of value that can have positive impact to ongoing geospatial information management by keeping systems and solutions cost effective and adaptive to change:

* Establishing and participating in a _*Standards Review Program*_ to maintain currency with new and emerging geospatial standards.
* Engaging with _*Communities of Practice (COP)*_ to share experiences and benefit from success stories and lessons learned by other community members that are implementing standards-based solutions.

=== Standards Review Program

A standards review program is a plan and process for implementing new and maintaining existing standards. SDOs typically have a form of standards review program, which over time leads to new standards and improvements to existing standards.

New and improved standards are driven by user community requirements. This is a reason for engaging with the standardization process. There may be opportunities for users and implementers of standards to engage and ensure that their requirements are captured in the standardization process, and those participating in standards review can serve as effective intermediaries between the user and standards bodies to ensure that requirements are properly articulated and addressed. Furthermore, SDOs may periodically update existing standards to address extended capabilities or to correct issues, or to provide additional guidance on implementation.

The standardization landscape also changes as technology and software development methods change. The http://ogcapi.ogc.org/[OGC API modernization] activity, for example, is aimed in part at adapting the existing OGC Web Services (OWS) standards to the current application development environment. OGC APIs will propose (but not mandate) the use of OpenAPI for describing API endpoints. This should improve the ease with which client applications can be created to use APIs. The OGC APIs will also be compatible with existing OWS standards.

International open standards may evolve from wide-scale implementation of proprietary specifications. Increasingly, organizations are submitting these _de facto_ standards to SDOs to be formally endorsed as Community standards or for consideration as international open standards. From an OGC perspective, Community standards can serve two purposes, to:

* Bring de facto standards from the larger geospatial community to be a stable reference point that can normatively referenced by governments and other organizations.
* Bring new, but implemented, standards to the OGC to form the basis for further refinement and development of interoperability between other OGC standards.footnote::[https://www.ogc.org/standards/community]

The http://www.ogc.org/standards/i3s[_OGC Indexed 3D Scene Layers (I3S_]_)_ and http://www.ogc.org/standards/3DTiles[_OGC 3DTiles_] standards submitted by OGC industry members followed this route. For a list of OGC Community Standards, visit http://www.ogc.org/standards/community[www.ogc.org/standards/community]

As changes to standards will likely occur during the lifecycle of a system, it is important that persons responsible for planning, acquisition and maintenance of systems are aware of these changes. Several nations have in place comprehensive standards review programs which monitor the standards environment and recommend / endorse new and updated standards to keep pace with new community needs and key information and technology market advancements. It is recommended to keep up-to-date with and align to the relevant national standards review programs and even consider becoming involved in the standardization process if the relevant review program invites participation from organizations as stakeholders.

Examples of national and supranational bodies responsible for standards review programs are:

* FGDC Standards Working Group (US) https://www.fgdc.gov/standards/organization/FGDC-SWG/index_html[https://www.fgdc.gov/standards/organization/FGDC-SWG/index\_html]
* Geonovum (the Netherlands) https://www.geonovum.nl/[https://www.geonovum.nl/] with membership of Forum Standaardisatie https://forumstandaardisatie.nl/[https://forumstandaardisatie.nl/]
* GeoConnections (Canada) https://www.nrcan.gc.ca/science-data/science-research/earth-sciences/geomatics/canadas-spatial-data-infrastructure/10783[https://www.nrcan.gc.ca/science-data/science-research/earth-sciences/geomatics/canadas-spatial-data-infrastructure/10783]
* National System of Statistical and Geographical Information (Sistema Nacional de Informacion Estadistica y Geográfica - SNIEG) (INEGI-Mexico)

http://www./[www.]snieg.mx/scn-acerca-de/

* INSPIRE (European Union) https://inspire.ec.europa.eu/[https://inspire.ec.europa.eu/] Community Forum https://inspire.ec.europa.eu/inspire-helpdesk[https://inspire.ec.europa.eu/inspire-helpdesk]

=== Communities of Practice

An effective approach for ongoing management of systems and solutions that implement open standards is to network with representatives from other organizations at the national and international levels. By sharing experiences in implementing standards-based geospatial information management capabilities, organizations benefit from the successes and lessons learned by others. The SDO community engages with a range of Communities of Practice (CoP) such as Aviation, Agriculture, Energy and Utilities, Marine, Earth Systems, and Land Administration. These and other CoPs participate in OGC, ISO/TC 211 and IHO as well as in professional associations to align to a common set of standards and good practices for information sharing.

For example, there are international programs working to bring together the world's national geological surveys and soils organizations as CoPs in order to agree on a common, federated approach for sharing globally the vital information these organizations produce and maintain at the national level.

http://www.onegeology.org/[*One Geology*] is an association that brings together national geological surveys and cooperating international organizations to address its mission to '*Make web-accessible the best available geological and other geoscience data worldwide at the best possible scales, starting with at least 1:1 million scale.'* National geologic data is integrated over an area of interest and made available over the web based on a well-documented OGC web services standards architecture
footnote::[See http://www.onegeology.org/technical_progress/technical.html].

Similarly, http://www.fao.org/global-soil-partnership/areas-of-work/soil-information-and-data/en/[*The Global Soils Information System (GLOSIS)*], part of the UN Food and Agriculture Organization Global Soil Partnership, employs OGC web services to connect national soils data for access through a common web services framework.

Many CoPs exist at the national level to facilitate communication, develop good practice documentation and guidelines, and often act as a conduit between global CoP and/or Standards Organizations.

http://ardc.edu.au/[*The Australian Research Data Commons (ARDC)*]is a transformational initiative that enables Australian research community and industry access to nationally significant, leading edge data intensive eInfrastructure, platforms, skills, and collections of high-quality data. The ARDC facilitates the work of many CoPs as a platform for information exchange, good practice advancement, problem solving and peer support. htps://ardc.edu.au/resources/communities-of-practice/

https://www.esipfed.org/[*Earth Science Information Partners*] https://www.esipfed.org/[(] https://www.esipfed.org/[*ESIP*] https://www.esipfed.org/[)] is a community of data and https://en.wikipedia.org/wiki/Information_technology[information technology] practitioners that come together to coordinate Earth science https://en.wikipedia.org/wiki/Interoperability[interoperability] efforts. ESIP enables and supports high quality virtual and in-person collaborations amongst cross-domain data professionals on common data challenges and opportunities ( https://www.esipfed.org/get-involved/collaborate[https://www.esipfed.org/get-involved/collaborate]).

Another important example is illustrated in the power of integrating statistical and geospatial information for the production and dissemination of location relevant statistics. The integration includes geocoding of statistics, spatial analysis, and creating statistical maps. Several governmental bodies are responsible for supporting the integration of statistical and geospatial information, and provide

* As the coordinating body of Mexico's National System of Statistical and Geographic Information (SNIEG), INEGI issues and provides the technical regulations for coordination and integration of statistical and geographical information. The https://en.www.inegi.org.mx/temas/mg/[] https://en.www.inegi.org.mx/temas/mg/[National Geostatistical Framework] of Mexico drives Mexico's national housing inventory, delineation of metropolitan areas and human settlements, school census data, and economic units among other entities.
* Within Eurostat, the Geographical Information System of the Commission (GISCO) is for improvement of the integration of statistical and geospatial information at the EU level. It seeks to promote the use of geographical information and the GIS within the European Statistical System (ESS) and the EU-Commission (see: https://ec.europa.eu/eurostat/web/gisco[] https://ec.europa.eu/eurostat/web/gisco[https://ec.europa.eu/eurostat/web/gisco]).

Eurostat and Mexico along with many other nations are heavily involved as a CoP in the activities of UN-GGIM, with focus on advancing a http://ggim.un.org/meetings/GGIM-committee/9th-Session/documents/The_GSGF.pdf[] http://ggim.un.org/meetings/GGIM-committee/9th-Session/documents/The_GSGF.pdf[Global Statistical Geospatial Information Framework documen]t.

The technical documents and insight offered by these and other CoPs can be of great value to organizations seeking to manage services that are interoperable within the organization and across organizations from the local to international level.

https://drive.google.com/file/d/14cmwQxcbrvTxxW1YspsbFOrM5R36zFnu/view?usp=sharing[Appendix 7] summarizes some of the key CoPs represented in the OGC, ISO/TC 211 and IHO, along with references to various professional associations that can be an excellent resource for gaining understanding of current and emerging community requirements for data sharing, exchanging community implementation good practices and lessons learned, and in identifying new standards needs and opportunities. In addition to a range of user-community oriented CoPs, the table also includes CoPs that bring together expertise on key geospatial technology areas such as Sensors and IoT, Artificial Intelligence and Machine Learning. These communities offer additional opportunities to learn about emerging standards-based technologies that may have benefit to an organization.
